title: Laser cut stencils for decorating food
hero_image: images/banner.png
description: Use the hackspace workhorse to make professional-looking edible treats
theme: blue # possible values: blue, green, navy, orange, red, turquoise, violet, yellow
duration: 2 # possible values: 1, 2 or 3
listed: false
ingredient: false
copyedit: false
curriculum: 
interests: 
technologies: 
site_areas: HackSpace
steps:
  - title: Introduction
  - title: What you will need
  - title: Step title
